<?php
/** @var \Mage4\TilesGallery\Block\Widget\Gallery $block */
?>

<div class="product-timer">
    <div class="owner-product">
        <h3 class="title">Best Sellers</h3>
    </div>
    <div class="row img-top-block">
        <div class="col-12 col-sm-6 cot">
            <a href="<?= $block->escapeHtml($block->getData('tile_url_1')) ?>">
                <img class="lazyload loaded" src="<?= $block->escapeHtml($block->getData('image_1')) ?>" data-src="https://stage.theskytourism.com/media/wysiwyg/Rectangle_224.png" alt="">
            </a>
            <span style="background-color: <?= $block->escapeHtml($block->getData('category_color_1')) ?>" ><?= $block->escapeHtml($block->getData('category_name_1')) ?></span>
            <span style="background-color: <?= $block->escapeHtml($block->getData('tag_color_1')) ?>" ><?= $block->escapeHtml($block->getData('tag_name_1')) ?></span>
        </div>
        <div class="col-12 col-sm-6 cot">
            <a href="<?= $block->escapeHtml($block->getData('tile_url_2')) ?>">
                <img class="lazyload loaded" src="<?= $block->escapeHtml($block->getData('image_2')) ?>" data-src="https://stage.theskytourism.com/media/wysiwyg/Rectangle_225_11zon.jpg" alt="">
            </a>
            <span style="background-color: <?= $block->escapeHtml($block->getData('category_color_2')) ?>" ><?= $block->escapeHtml($block->getData('category_name_2')) ?></span>
            <span style="background-color: <?= $block->escapeHtml($block->getData('tag_color_2')) ?>" ><?= $block->escapeHtml($block->getData('tag_name_2')) ?></span>
        </div>
    </div>
    <div class="row img-bottom-block">
        <div class="col-12 col-sm-4 cot">
            <a href="<?= $block->escapeHtml($block->getData('tile_url_3')) ?>">
                <img class="lazyload loaded" src="<?= $block->escapeHtml($block->getData('image_3')) ?>" data-src="https://stage.theskytourism.com/media/wysiwyg/Rectangle_226_11zon.jpg" alt="">
            </a>
            <span style="background-color: <?= $block->escapeHtml($block->getData('category_color_3')) ?>" ><?= $block->escapeHtml($block->getData('category_name_3')) ?></span>
            <span style="background-color: <?= $block->escapeHtml($block->getData('tag_color_3')) ?>" ><?= $block->escapeHtml($block->getData('tag_name_3')) ?></span>
        </div>
        <div class="col-12 col-sm-4 cot">
            <a href="<?= $block->escapeHtml($block->getData('tile_url_4')) ?>">
                <img class="lazyload loaded" src="<?= $block->escapeHtml($block->getData('image_4')) ?>" data-src="https://stage.theskytourism.com/media/wysiwyg/Rectangle_227_11zon.jpg" alt="">
            </a>
            <span style="background-color: <?= $block->escapeHtml($block->getData('category_color_4')) ?>" ><?= $block->escapeHtml($block->getData('category_name_4')) ?></span>
            <span style="background-color: <?= $block->escapeHtml($block->getData('tag_color_4')) ?>" ><?= $block->escapeHtml($block->getData('tag_name_4')) ?></span>
        </div>
        <div class="col-12 col-sm-4 cot">
            <a href="<?= $block->escapeHtml($block->getData('tile_url_5')) ?>">
                <img class="lazyload loaded" src="<?= $block->escapeHtml($block->getData('image_5')) ?>" data-src="https://stage.theskytourism.com/media/wysiwyg/Rectangle_228_11zon.jpg" alt="">
            </a>
            <span style="background-color: <?= $block->escapeHtml($block->getData('category_color_5')) ?>" ><?= $block->escapeHtml($block->getData('category_name_5')) ?></span>
            <span style="background-color: <?= $block->escapeHtml($block->getData('tag_color_5')) ?>" ><?= $block->escapeHtml($block->getData('tag_name_5')) ?></span>
        </div>
        <div class="col-12 col-sm-4 cot">&nbsp;</div>
    </div>
</div>
