<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>STC pay | دفع عن طريق  STC</title>
	<meta name="description" content="STC pay | دفع عن طريق  STC">
	<meta name="author" content="RTLSOL">
	 <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css" integrity="sha384-vus3nQHTD+5mpDiZ4rkEPlnkcyTP+49BhJ4wJeJunw06ZAp+wzzeBPUXr42fi8If" crossorigin="anonymous">
	 <style type="text/css">
	 	.bg-black{
	 		background-color: #000;
	 	}
	 	.d-flex-2{
	 		flex-wrap: wrap;
	 	}
	 	#source-cvc{
	 		max-width: 80px;
	 	}
	 		 #source-month{
	 	margin-bottom: 4px;
	 }
	 	form img{
	 		max-width:30px;height:20px;
	 	}
	 	form input+img{
	 		margin-top: 11px;
	 	}
	 	 @media only screen and (min-width: 526px) {
	 	
	 	.d-flex-2{
	 		flex-wrap: wrap;
	 	} 
	 	.d-flex-2 input{
	 		flex: 0 50%;
	 		flex-shrink: 1;
	 	}
	 #source-month{
	 	margin-bottom: 0px;
	 }
	 .d-inline-blk{
	 	display: inline-block;
	 }
	 }
	 input{
	 	direction: rtl;
	 }
	 </style>
</head>
<body>
<div class="container">
<?php
$amount 		= isset($_GET['amount']) ? $_GET['amount'] : "";
$description    = "Description";
$scheme 		= $_SERVER['REQUEST_SCHEME'] . '://';
$baseUrl		= $scheme . $_SERVER['SERVER_NAME'];
?>


<form accept-charset="UTF-8" action="https://api.moyasar.com/v1/payments.html" method="POST" class="w-100 mt-4">
    <input type="hidden" name="publishable_api_key" value="pk_live_U275ndBphFfWQ4heAiSEhe3T3U3SgHKDmNNDkdY9" />
    <input type="hidden" name="source[type]" value="creditcard" />
    <input type="hidden" name="source[3ds]" value="true" />
    <input type="hidden" name="description" value="<?php echo $description;  ?>" />
    <input type="hidden" name="amount" value="<?php echo $amount;  ?>" />
    <input type="hidden" name="currency" value="SAR" />
    <input name="callback_url" type="hidden" value="<?php echo $baseUrl;?>/webpages/index/Status"  />

    <div class="form-group">
    	<label data-bind="attr: {'for': getCode()}" class="label" for=""><span>مدى أو البطاقة الإئتمانية</span>
            <img src="<?php echo $this->getViewFileUrl('Baytonia_Webpages::images/visa.png'); ?>" id="visa" alt="visa"/>
            <img src="<?php echo $this->getViewFileUrl('Baytonia_Webpages::images/mastercard.png'); ?>" id="mastercard" alt="mastercard"/>
            <img src="<?php echo $this->getViewFileUrl('Baytonia_Webpages::images/mada.png'); ?>" id="amex" alt="mada"/>
            
        </label>
    </div>
    <div class="form-group">
        <label for="source-name">إسم صاحب البطاقة</label>
        <input type="text" id="source-name" class="form-control" name="source[name]" required/>
    </div>
    <div class="form-group">
        <label for="source-number">رقم بطاقه الائتمان</label>
        <input type="text" id="source-number" class="form-control" name="source[number]" maxlength="16" required/>
    </div>
    <div class="group d-inline-block">
        <label for="source-month">تاريخ إنتهاء الصلاحية</label>
        <div class="d-flex d-flex-2">
        <input type="text" id="source-month" class="form-control" name="source[month]"  maxlength="2" placeholder="02" required/>
        <input type="text" id="source-year" class="form-control" name="source[year]" maxlength="4" placeholder="2021" required/>
    </div>
    </div>
    <div class="group d-inline-block">
    	<label for="source-cvc" class="d-block">رقم التحقق من البطاقة</label>
    	<div class="d-flex d-flex-2">
            <input type="text" id="source-cvc" class="form-control" name="source[cvc]" placeholder="***" required/>
            <img class="mr-2" src="<?php echo $this->getViewFileUrl('Baytonia_Webpages::images/card-cvv-baytonia.png'); ?>">
        </div>
    </div>
    <button class="w-100 mt-3 bg-black p-2 pointer btn" type="submit"><span class="text-white">تأكيد الطلب</span></button>
</form>
</div>
</body>
</html>
